Dev 52 implement voting logic
backendsnakes/poll_service_api pull request #10
Opened 2024-08-16 12:53 UTC by hagp55

2024-08-17 09:07 UTC, kaziamov requested changes

2024-08-17 09:07 UTC, kaziamov commented on app/poll/service.py
> +            return False
Функция возвращает тип не указанный в аннотации. Подумай правильная ли логика что у нас ест ьвариант либо возвращается Poll, либо False

2024-08-17 09:07 UTC, kaziamov commented on app/tests/poll/test_vote.py
> +from random import choice
В коде есть функция update_vote, но нет тестов на нее

2024-08-17 09:07 UTC, kaziamov commented on app/poll/service.py
> +        raise HTTPException(
Может стоит как то стандартизировать обработку ошибок?

2024-08-18 04:34 UTC, hagp55 commented on app/tests/poll/test_vote.py
> +from random import choice
у меня покрытие тестов 99%

2024-08-18 17:08 UTC, ApriCotBrain approved these changes

2024-08-19 06:27 UTC, RomanPecheritsa approved these changes

2024-08-19 08:12 UTC, FuneralKitty approved these changes
Done

2024-08-19 08:28 UTC, kaziamov approved these changes

2024-08-19 10:49 UTC, merged