Edit README.md
backendsnakes/poll_service_api pull request #18
Opened 2024-08-30 09:20 UTC by hagp55

2024-08-30 10:43 UTC, RomanPecheritsa approved these changes

2024-08-30 14:53 UTC, kaziamov requested changes

2024-08-30 14:53 UTC, kaziamov commented on docker-compose.yml
> +      restart: always
Точно ли нужна опция restart?

2024-08-30 15:33 UTC, hagp55 commented on docker-compose.yml
> +      restart: always
Ну почему бы и нет? Ну можно и убрать 😁

2024-08-30 18:32 UTC, kaziamov commented on docker-compose.yml
> +      restart: always
Ну мои ты знаешь зачем эта опция и какие есть особенности использования, то можешь оставить

2024-08-31 02:38 UTC, hagp55 commented on docker-compose.yml
> +      restart: always
Я знаю для чего, обычно либо restart always либо unless-stopped

2024-08-31 08:53 UTC, svereshagin approved these changes

2024-08-31 15:27 UTC, kaziamov approved these changes

2024-08-31 15:41 UTC, merged